'use client'

// Style card of the CV style selector (/create-cv, step 2). Visual direction: the CEO's
// reference video (real CV filling the card, floating pill, overlaid info panel, CTA on
// hover) with the design-system tokens (Referencias/Momentum_CV_Direccion_Visual…).

import { useState } from 'react'

// The 7 styles offered in the selector.
export const ESTILOS = [
  { id: 'harvard',        nombre: 'Harvard',                 tagline: 'Clásico, estructurado, enfocado en logros medibles.',              tags: ['Consultoría', 'Finanzas', 'Banca'],          iconBg: '#1F3A5F', accent: '#4B6BFB', isPro: false },
  { id: 'stanford',       nombre: 'Stanford',                tagline: 'Puente entre rigor académico y mentalidad de producto.',            tags: ['Startups', 'Product', 'MBA'],                iconBg: '#8C1515', accent: '#22C55E', isPro: false },
  { id: 'silicon-valley', nombre: 'Silicon Valley',          tagline: 'Directo, técnico, sin relleno. Cada bullet prueba escala.',          tags: ['Developers', 'Data', 'Infra/SRE'],           iconBg: '#2563EB', accent: '#A855F7', isPro: true  },
  { id: 'tech',           nombre: 'Tech',                    tagline: 'Técnico y legible para reclutadores no técnicos.',                  tags: ['Software', 'DevOps', 'QA'],                  iconBg: '#0F766E', accent: '#0F766E', isPro: true  },
  { id: 'minimalist',     nombre: 'Minimalista',             tagline: 'El CV mismo es una muestra de tu criterio estético.',               tags: ['Diseño', 'Editorial', 'Arquitectura'],       iconBg: '#1A1A1A', accent: '#888888', isPro: true  },
  { id: 'europass',       nombre: 'Europeo (Europass)',      tagline: 'El formato oficial de la Unión Europea, en 36 países.',             tags: ['Europa', 'Públicas', 'ONGs'],                iconBg: '#003399', accent: '#003399', isPro: true  },
  { id: 'executive',      nombre: 'Ejecutivo',               tagline: 'Para C-suite y senior leadership. Métricas de P&L, no tareas.',     tags: ['CEO', 'Directores', 'VP'],                   iconBg: '#1C1917', accent: '#EF4444', isPro: true  },
] as const

export type EstiloId = typeof ESTILOS[number]['id']

export interface EstiloMeta {
  id: string
  nombre: string
  tagline: string
  tags: readonly string[]
}

function handleOptionKeyDown(e: React.KeyboardEvent, onActivate: () => void) {
  if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onActivate() }
}

function CheckIcon({ size = 10, color = '#16A34A' }: { size?: number; color?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="m4 12 5 5L20 6"/>
    </svg>
  )
}

// Real-template samples (spec §11) for every style, generated by `npm run samples`
// (a test fails if one goes stale).
export const MUESTRAS: Record<string, { portada: string; completo: string }> = Object.fromEntries(
  (['harvard', 'stanford', 'silicon-valley', 'tech', 'minimalist', 'europass', 'executive'] as const)
    .map(id => [id, { portada: `/muestras/${id}-portada.png`, completo: `/muestras/${id}-completo.png` }]),
)

// Visual direction tokens (Referencias/Momentum_CV_Direccion_Visual…, §16).
export const DS = {
  primary: '#4A67FF', primaryHover: '#3D56E8', primarySoft: '#EEF1FF',
  ink: '#0B1B36', text: '#475569', secondary: '#64748B',
  border: '#E7EBF3', shadow: '0 8px 30px rgba(15, 35, 75, 0.06)',
} as const

export function EstiloCard({ estilo, selected, onSelect, locked, onVerEjemplo }: {
  estilo: EstiloMeta; selected: boolean; onSelect: () => void; locked: boolean; onVerEjemplo: () => void
}) {
  const muestra = MUESTRAS[estilo.id]
  const [hover, setHover] = useState(false)
  const [focusIn, setFocusIn] = useState(false)
  // The panel grows and shows "Ver ejemplo" on hover, keyboard focus or selection
  // (touch screens have no hover).
  const expanded = hover || focusIn || selected
  return (
    <div
      role="radio"
      aria-checked={selected}
      aria-label={`${estilo.nombre}. ${estilo.tagline}`}
      tabIndex={0}
      className="focus-ring"
      onClick={onSelect}
      onKeyDown={e => handleOptionKeyDown(e, onSelect)}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      onFocus={() => setFocusIn(true)}
      onBlur={e => { if (!e.currentTarget.contains(e.relatedTarget as Node | null)) setFocusIn(false) }}
      style={{
        position: 'relative', height: 380, borderRadius: 16, overflow: 'hidden', cursor: 'pointer',
        background: '#FFFFFF',
        border: `${selected ? 2 : 1}px solid ${selected ? DS.primary : DS.border}`,
        boxShadow: selected ? `0 0 0 4px ${DS.primarySoft}, ${DS.shadow}` : hover ? '0 12px 36px rgba(15, 35, 75, 0.10)' : DS.shadow,
        transform: hover && !selected ? 'translateY(-3px)' : 'none',
        transition: 'transform .22s cubic-bezier(0.4,0,0.2,1), box-shadow .22s, border-color .22s',
      }}
    >
      {/* The real CV fills the card (Momentum ≠ the user's CV: no brand on the document). */}
      {muestra && (
        // eslint-disable-next-line @next/next/no-img-element -- static sample in /public
        <img src={muestra.completo} alt="" loading="lazy" aria-hidden="true"
          // Full width, top-aligned, never cropped at the sides.
          style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: 'auto', display: 'block' }} />
      )}

      {/* Who it's for (from "Ideal para") — never invented claims. */}
      <span style={{
        position: 'absolute', left: 12, top: 118, padding: '6px 12px', borderRadius: 999,
        background: DS.primarySoft, color: DS.primaryHover, fontSize: 12.5, fontWeight: 600,
        boxShadow: '0 4px 14px rgba(15, 35, 75, 0.10)', border: '1px solid #DDE3FF', whiteSpace: 'nowrap',
      }}>
        {estilo.tags.slice(0, 2).join(' · ')}
      </span>

      {selected && (
        <div aria-hidden="true" style={{
          position: 'absolute', top: 12, right: 12, width: 26, height: 26, borderRadius: '50%',
          background: DS.primary, display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 2px 8px rgba(74,103,255,.4)',
        }}>
          <CheckIcon size={12} color="#fff" />
        </div>
      )}

      {/* Info panel over the lower part of the CV */}
      <div style={{
        position: 'absolute', left: 10, right: 10, bottom: 10, padding: '12px 14px',
        background: '#FFFFFF', borderRadius: 12, border: `1px solid ${DS.border}`,
        boxShadow: '0 -4px 24px rgba(15, 35, 75, 0.08)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
          <span style={{ fontSize: 15, fontWeight: 700, color: DS.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{estilo.nombre}</span>
          {locked && (
            <span style={{ fontSize: 10.5, fontWeight: 600, padding: '2px 8px', borderRadius: 999, background: DS.primarySoft, color: DS.primaryHover, flexShrink: 0 }}>
              Pro
            </span>
          )}
        </div>
        <div style={{ fontSize: 12, color: DS.secondary, lineHeight: 1.45 }}>{estilo.tagline}</div>
        {muestra && (
          <div style={{ display: 'grid', gridTemplateRows: expanded ? '1fr' : '0fr', transition: 'grid-template-rows .22s cubic-bezier(0.4,0,0.2,1)' }}>
            <div style={{ overflow: 'hidden' }}>
              <button type="button" tabIndex={expanded ? 0 : -1}
                onClick={e => { e.stopPropagation(); onVerEjemplo(); }}
                onKeyDown={e => e.stopPropagation()}
                onMouseEnter={e => (e.currentTarget.style.background = DS.primaryHover)}
                onMouseLeave={e => (e.currentTarget.style.background = DS.primary)}
                style={{
                  width: '100%', marginTop: 10, padding: '10px 14px', borderRadius: 12, border: 'none', cursor: 'pointer',
                  background: DS.primary, color: '#fff', fontSize: 13.5, fontWeight: 600, transition: 'background .15s',
                }}>
                Ver ejemplo
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
